name: Download Docker Image
on: workflow_dispatch # 手动触发
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Pull and Save Image
        run: |
          docker pull calciumion/new-api:latest
          docker save calciumion/new-api:latest -o new-api.tar
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: new-api-image
          path: new-api.tar
